services:
  mosdns:
    image: jeffok/mosdns:latest
    container_name: mosdns
    network_mode: host
    restart: unless-stopped
    volumes:
      - mosdns-data:/etc/mosdns
      - ./certs:/etc/mosdns/certs:ro
    env_file: .env

volumes:
  mosdns-data:
