services:
  mosdns:
    image: jeffok/mosdns:latest
    container_name: mosdns
    network_mode: host
    restart: unless-stopped
    volumes:
      - .:/etc/mosdns
    environment:
      TZ: ${TZ:-Asia/Shanghai}
      ROS_HOST: ${ROS_HOST:-}
      ROS_PASS: ${ROS_PASS:-}
      DNS_SERVER: ${DNS_SERVER:-10.100.89.3}
