# 默认 server：80 重定向，443 默认

server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;
    server_name _;
    ssl_certificate /etc/nginx/conf.d/ssl/jeffok.com.crt;
    ssl_certificate_key /etc/nginx/conf.d/ssl/jeffok.com.key;
    location / {
        return 204;
    }
}
